/* Autogenerated file. Do not edit manually. */

import { defineComponent, Type as RecsType, World } from "@latticexyz/recs";

export function defineContractComponents(world: World) {
  return {
    GameStats: (() => {
      const name = "GameStats";
      return defineComponent(
        world,
        {
          block_number: RecsType.Number,
          tick_number: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    AuthStatus: (() => {
      const name = "AuthStatus";
      return defineComponent(
        world,
        {
          is_authorized: RecsType.Boolean,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    AuthRole: (() => {
      const name = "AuthRole";
      return defineComponent(
        world,
        {
          id: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
  };
}
